Show loading indicator when nft tracks are being fetched from the network
projectNEWM/newm-mobile pull request #267
Opened 2024-06-26 15:03 UTC by newmskywalker

2024-06-26 15:26 UTC, cristhianescobar commented on android/app-newm/src/main/java/io/newm/screens/library/NFTLibraryPresenter.kt
> +        }.collectAsRetainedState(initial = emptyList())
Interesting, so it was not working as expected because we were using `collectAsState` as opposed to `collectAsRetainedState`?

2024-06-26 15:33 UTC, cristhianescobar commented on shared/src/commonMain/kotlin/io.newm.shared/public/usecases/HasEmptyWalletUseCase.kt
> +interface HasEmptyWalletUseCase {
Should we merge the functionality with `HasWalletConnectionsUseCase`? Since they are both very similar?

2024-06-26 15:34 UTC, cristhianescobar requested changes
Let's combine the usecases since they seem to do the same or similar things.

2024-06-26 16:24 UTC, newmskywalker commented on shared/src/commonMain/kotlin/io.newm.shared/public/usecases/HasEmptyWalletUseCase.kt
> +interface HasEmptyWalletUseCase {
Could someone have a wallet connection without NFTs?

2024-06-26 16:26 UTC, newmskywalker commented on android/app-newm/src/main/java/io/newm/screens/library/NFTLibraryPresenter.kt
> +        }.collectAsRetainedState(initial = emptyList())
it's not working because the database is always empty when we're initially loading the NFTs which results in the UI showing the empty state 

The retained state just ensures we don't make the same call every time the presenter is recreated (similar to how an Android view model would handle this)

2024-06-27 06:01 UTC, cristhianescobar commented on shared/src/commonMain/kotlin/io.newm.shared/public/usecases/HasEmptyWalletUseCase.kt
> +interface HasEmptyWalletUseCase {
Yes, there could be an empty wallet with no NFTs

2024-06-30 21:06 UTC, newmskywalker commented on shared/src/commonMain/kotlin/io.newm.shared/public/usecases/HasEmptyWalletUseCase.kt
> +interface HasEmptyWalletUseCase {
Combined it with the `WalletNFTTracksUseCase` since they're more aligned in functionality. Let me know if that works!

2024-07-01 03:39 UTC, cristhianescobar approved these changes

2024-07-01 03:39 UTC, merged