Make iOS compile against latest shared changes
projectNEWM/newm-mobile pull request #306
Opened 2024-08-16 11:02 UTC by newmskywalker

2024-08-16 18:46 UTC, martyu requested changes

2024-08-16 18:46 UTC, martyu commented on shared/src/commonMain/kotlin/io.newm.shared/internal/implementations/WalletNFTTracksUseCaseImpl.kt
> -        return mapErrors {
Whyd this get removed?

2024-08-16 18:46 UTC, martyu commented on shared/src/commonMain/kotlin/io.newm.shared/public/usecases/WalletNFTTracksUseCase.kt
> -    @Throws(KMMException::class, CancellationException::class)
Same here

2024-08-16 21:24 UTC, newmskywalker commented on shared/src/commonMain/kotlin/io.newm.shared/public/usecases/WalletNFTTracksUseCase.kt
> -    @Throws(KMMException::class, CancellationException::class)
This fixes the error we were talking about on slack. 

![image](https://github.com/user-attachments/assets/6f9675f2-84a4-4e51-ba80-458dc4587228)

It looks like throwing functions cannot return optional values. I looked at this specific function and it doesn't throw. It just returns null if the track is not found in the db. So I figured the easiest way to fix the issue was to make the function non-throwing. Let me know if that doesn't work!

2024-08-21 17:57 UTC, newmskywalker commented on shared/src/commonMain/kotlin/io.newm.shared/public/usecases/WalletNFTTracksUseCase.kt
> -    @Throws(KMMException::class, CancellationException::class)
@martyu any additional thoughts on this PR?

2024-08-24 04:42 UTC, cristhianescobar submitted a review, later dismissed

2024-08-30 15:38 UTC, cristhianescobar commented on shared/src/commonMain/kotlin/io.newm.shared/public/usecases/WalletNFTTracksUseCase.kt
> -    @Throws(KMMException::class, CancellationException::class)
@martyu are we good to merge this PR?

2024-08-31 14:33 UTC, merged