CU-2nuqkfx - Set up Common codeowners
projectNEWM/newm-mobile pull request #60
Opened 2022-04-03 23:29 UTC by martyu

CU-2nuqk3u - Set up iOS github team and codeowners
CU-2nuqk36 - Set up Android github team and codeowners

Need to set up github teams before merging.  I don't have permissions to do that.

2022-04-03 23:29 UTC, j-mateo commented
Task linked: [CU-2nuqk36 Set up Android github team and codeowners](https://app.clickup.com/t/2nuqk36)

2022-04-03 23:29 UTC, j-mateo commented
Task linked: [CU-2nuqk3u Set up iOS github team and codeowners](https://app.clickup.com/t/2nuqk3u)

2022-04-03 23:29 UTC, j-mateo commented
Task linked: [CU-2nuqkfx Set up Common codeowners](https://app.clickup.com/t/2nuqkfx)

2022-04-04 04:22 UTC, cristhianescobar commented on .github/CODEOWNERS
> +/newm-mobile/shared/androidMain @newm-mobile/ios
Should this be `@newm-mobile/android`

2022-04-04 04:35 UTC, cristhianescobar requested changes

2022-04-04 04:35 UTC, cristhianescobar commented on .github/CODEOWNERS
> +
Should this be @newm-mobile/android

2022-04-05 04:41 UTC, cristhianescobar approved these changes
💯  LGTM!

2022-04-05 18:39 UTC, merged